import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { motion, useReducedMotion } from 'motion/react';
import {
  MapPin,
  Search,
  PhoneCall,
  Sparkles,
  Map,
  Contact,
  Zap,
  Globe2,
  BadgeCheck,
  ArrowRight,
  Star,
  Phone,
  ShieldCheck,
} from 'lucide-react';
import Layout from '../layout/Layout';
import { useAuth } from '../hooks/useAuth';

const HOW_IT_WORKS = [
  {
    icon: MapPin,
    title: 'Set your location',
    desc: 'Pick your state and district, then type your city or town. Takes ten seconds.',
  },
  {
    icon: Search,
    title: 'Search businesses',
    desc: 'We sweep Google Maps for shops, malls, eateries and services around you.',
  },
  {
    icon: PhoneCall,
    title: 'Connect directly',
    desc: 'Get phone numbers, locations and an AI summary — then reach out.',
  },
];

// Bento-style features with span hints for a non-uniform, designed grid.
const FEATURES = [
  {
    icon: Map,
    title: 'Google Maps powered',
    desc: 'Accurate, fresh listings pulled straight from Google Places across every category.',
    span: 'lg:col-span-2',
    accent: true,
  },
  {
    icon: Sparkles,
    title: 'AI business summaries',
    desc: 'A friendly, instant read on each place — generated by a local open-source model.',
    span: '',
  },
  {
    icon: Contact,
    title: 'Contact info surfaced',
    desc: 'Phone numbers and addresses up front.',
    span: '',
  },
  {
    icon: Globe2,
    title: 'Offline-first discovery',
    desc: 'Filter to businesses with no website — the ones the web forgot.',
    span: '',
  },
  {
    icon: Zap,
    title: 'Fast & cached',
    desc: 'Parallel lookups and smart caching keep results instant.',
    span: '',
  },
];

const STATS = [
  { value: 10000, suffix: '+', label: 'Businesses indexed' },
  { value: 500, suffix: '+', label: 'Cities covered' },
  { value: 100, suffix: '%', label: 'Free forever' },
];

// Static sample cards for the hero product preview.
const PREVIEW_CARDS = [
  {
    name: 'Sharma General Stores',
    category: 'Shops',
    phone: '+91 98765 43210',
    rating: 4.6,
    reviews: 214,
  },
  {
    name: 'Annapurna Family Restaurant',
    category: 'Restaurants',
    phone: '+91 91234 56780',
    rating: 4.8,
    reviews: 532,
  },
  {
    name: 'City Care Pharmacy',
    category: 'Healthcare',
    phone: '+91 99887 76655',
    rating: 4.4,
    reviews: 98,
  },
];

/** Animated count-up that triggers when scrolled into view. */
const CountUp = ({ value, suffix }) => {
  const ref = useRef(null);
  const [display, setDisplay] = useState(0);
  const reduce = useReducedMotion();

  useEffect(() => {
    const node = ref.current;
    if (!node) return undefined;

    if (reduce) {
      setDisplay(value);
      return undefined;
    }

    let raf;
    let started = false;
    const duration = 1600;

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting && !started) {
            started = true;
            const start = performance.now();
            const tick = (now) => {
              const progress = Math.min((now - start) / duration, 1);
              const eased = 1 - Math.pow(1 - progress, 3);
              setDisplay(Math.round(eased * value));
              if (progress < 1) raf = requestAnimationFrame(tick);
            };
            raf = requestAnimationFrame(tick);
          }
        });
      },
      { threshold: 0.4 }
    );

    observer.observe(node);
    return () => {
      observer.disconnect();
      if (raf) cancelAnimationFrame(raf);
    };
  }, [value, reduce]);

  return (
    <span ref={ref}>
      {display.toLocaleString('en-IN')}
      {suffix}
    </span>
  );
};

/** The floating "app preview" panel shown beside the hero copy. */
const HeroPreview = ({ reduce }) => (
  <motion.div
    initial={reduce ? false : { opacity: 0, y: 30, rotate: -2 }}
    animate={{ opacity: 1, y: 0, rotate: 0 }}
    transition={{ duration: 0.6, delay: 0.2 }}
    className="relative mx-auto w-full max-w-md"
  >
    {/* Glow behind the panel */}
    <div
      aria-hidden="true"
      className="absolute -inset-6 -z-10 rounded-[2rem] bg-glow-primary blur-2xl"
    />
    <div className="card-base overflow-hidden p-4 sm:p-5">
      {/* Fake top bar */}
      <div className="mb-4 flex items-center gap-2">
        <span className="h-2.5 w-2.5 rounded-full bg-error/70" />
        <span className="h-2.5 w-2.5 rounded-full bg-primary/60" />
        <span className="h-2.5 w-2.5 rounded-full bg-accent/70" />
        <div className="ml-3 flex-1 rounded-lg bg-surface-2 px-3 py-1.5 text-xs text-text-muted">
          Businesses in Nashik, Maharashtra
        </div>
      </div>

      <div className="space-y-3">
        {PREVIEW_CARDS.map((c, i) => (
          <motion.div
            key={c.name}
            initial={reduce ? false : { opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.4, delay: 0.4 + i * 0.12 }}
            className="rounded-xl border border-border bg-surface-2 p-3.5"
          >
            <div className="flex items-start justify-between gap-2">
              <div className="font-display text-sm font-semibold text-text">
                {c.name}
              </div>
              <span className="pill border-accent/40 bg-accent/10 text-accent">
                <Globe2 className="h-3 w-3" />
                No Website
              </span>
            </div>
            <div className="mt-2 flex items-center gap-1.5 text-xs text-text-muted">
              <Phone className="h-3.5 w-3.5 text-accent" />
              {c.phone}
            </div>
            <div className="mt-2 flex items-center justify-between">
              <span className="pill border-primary/40 bg-primary/10 text-primary">
                {c.category}
              </span>
              <span className="flex items-center gap-1 text-xs text-text-muted">
                <Star className="h-3.5 w-3.5 fill-accent text-accent" />
                {c.rating} · {c.reviews}
              </span>
            </div>
          </motion.div>
        ))}
      </div>
    </div>

    {/* Floating AI-summary chip */}
    <motion.div
      initial={reduce ? false : { opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ duration: 0.4, delay: 0.9 }}
      className={`absolute -bottom-5 -right-3 max-w-[12rem] rounded-2xl border border-border bg-surface p-3 shadow-lg shadow-black/50 ${
        reduce ? '' : 'animate-float'
      }`}
    >
      <div className="mb-1 flex items-center gap-1.5 text-xs font-semibold text-primary">
        <Sparkles className="h-3.5 w-3.5" />
        AI summary
      </div>
      <p className="text-[11px] leading-snug text-text-muted">
        “A beloved neighbourhood store known for friendly service and fair
        prices…”
      </p>
    </motion.div>
  </motion.div>
);

const LandingPage = () => {
  const reduce = useReducedMotion();
  const { isAuthenticated, hasAddress } = useAuth();
  const featuresRef = useRef(null);

  const primaryTo = isAuthenticated
    ? hasAddress
      ? '/search'
      : '/address-setup'
    : '/signup';
  const primaryLabel = isAuthenticated ? 'Go to Search' : 'Get Started Free';

  const scrollToFeatures = () => {
    featuresRef.current?.scrollIntoView({
      behavior: reduce ? 'auto' : 'smooth',
      block: 'start',
    });
  };

  const container = {
    hidden: {},
    show: { transition: { staggerChildren: 0.08 } },
  };
  const item = {
    hidden: reduce ? { opacity: 1 } : { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { duration: 0.4 } },
  };

  return (
    <Layout>
      <Helmet>
        <title>Localify — Find the Hidden Businesses Your City Never Told You About</title>
        <meta
          name="description"
          content="Discover local businesses, shops, malls and services in your city — including the offline-only ones without websites. Contact details and AI summaries included, free forever."
        />
        <meta property="og:title" content="Localify — Discover Hidden Local Businesses" />
        <meta
          property="og:description"
          content="Find local shops, malls and services in your city, with phone numbers, maps and AI summaries."
        />
        <meta property="og:type" content="website" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Localify — Discover Hidden Local Businesses" />
        <meta
          name="twitter:description"
          content="Find local shops, malls and services in your city, with phone numbers, maps and AI summaries."
        />
      </Helmet>

      {/* HERO — background motion is provided site-wide by Layout */}
      <section className="relative overflow-hidden">

        <div className="mx-auto grid max-w-6xl items-center gap-12 px-4 pb-16 pt-8 sm:px-6 lg:grid-cols-2 lg:gap-8 lg:pb-24 lg:pt-12">
          {/* Left: copy */}
          <div className="text-center lg:text-left">
            <motion.span
              initial={reduce ? false : { opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4 }}
              className="pill mb-6 border-primary/40 bg-primary/10 text-primary"
            >
              <Sparkles className="h-3.5 w-3.5" />
              Powered by Google Maps + local AI
            </motion.span>

            <motion.h1
              initial={reduce ? false : { opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="text-balance font-display text-4xl font-extrabold leading-[1.05] tracking-tight text-text sm:text-5xl xl:text-6xl"
            >
              Find the{' '}
              <span className="bg-gradient-to-r from-primary via-accent to-primary bg-clip-text text-transparent">
                Hidden Businesses
              </span>{' '}
              Your City Never Told You About
            </motion.h1>

            <motion.p
              initial={reduce ? false : { opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              className="mx-auto mt-6 max-w-xl text-base text-text-muted sm:text-lg lg:mx-0"
            >
              Thousands of shops, malls and family-run businesses operate entirely
              offline. Localify uncovers them across your city, surfaces their
              contact details, and explains what they do with instant AI summaries.
            </motion.p>

            <motion.div
              initial={reduce ? false : { opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="mt-10 flex flex-col items-center gap-3 sm:flex-row lg:justify-start"
            >
              <motion.div whileTap={reduce ? undefined : { scale: 0.96 }}>
                <Link to={primaryTo} className="btn-primary px-7 py-3.5 text-base">
                  {primaryLabel}
                  <ArrowRight className="h-4 w-4" />
                </Link>
              </motion.div>
              <motion.button
                whileTap={reduce ? undefined : { scale: 0.96 }}
                type="button"
                onClick={scrollToFeatures}
                className="btn-ghost px-7 py-3.5 text-base"
              >
                See How It Works
              </motion.button>
            </motion.div>

            {/* Trust row */}
            <motion.div
              initial={reduce ? false : { opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5, delay: 0.35 }}
              className="mt-8 flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-xs text-text-muted lg:justify-start"
            >
              <span className="inline-flex items-center gap-1.5">
                <ShieldCheck className="h-4 w-4 text-accent" />
                No spam, ever
              </span>
              <span className="inline-flex items-center gap-1.5">
                <BadgeCheck className="h-4 w-4 text-accent" />
                Free forever
              </span>
              <span className="inline-flex items-center gap-1.5">
                <Zap className="h-4 w-4 text-accent" />
                Instant results
              </span>
            </motion.div>
          </div>

          {/* Right: product preview */}
          <div className="relative">
            <HeroPreview reduce={reduce} />
          </div>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="mx-auto max-w-6xl px-4 py-20 sm:px-6">
        <div className="mb-14 text-center">
          <span className="pill mb-3 border-accent/40 bg-accent/10 text-accent">
            How it works
          </span>
          <h2 className="text-balance font-display text-3xl font-bold text-text sm:text-4xl">
            Three steps from curiosity to a phone call
          </h2>
        </div>

        <motion.div
          variants={container}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true, amount: 0.2 }}
          className="relative grid gap-6 md:grid-cols-3"
        >
          {/* connecting line on desktop */}
          <div
            aria-hidden="true"
            className="absolute left-0 right-0 top-12 hidden h-px bg-gradient-to-r from-transparent via-border to-transparent md:block"
          />
          {HOW_IT_WORKS.map((step, i) => (
            <motion.div
              key={step.title}
              variants={item}
              className="card-base relative p-7"
            >
              <div className="mb-5 inline-grid h-12 w-12 place-items-center rounded-xl bg-gradient-to-br from-primary/20 to-accent/20 text-primary ring-1 ring-border">
                <step.icon className="h-6 w-6" />
              </div>
              <div className="mb-1 font-display text-sm font-bold text-accent">
                Step {i + 1}
              </div>
              <h3 className="font-display text-xl font-semibold text-text">
                {step.title}
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-text-muted">
                {step.desc}
              </p>
            </motion.div>
          ))}
        </motion.div>
      </section>

      {/* FEATURES — bento grid */}
      <section ref={featuresRef} className="scroll-mt-20 border-y border-border bg-surface/40">
        <div className="mx-auto max-w-6xl px-4 py-20 sm:px-6">
          <div className="mb-14 text-center">
            <span className="pill mb-3 border-primary/40 bg-primary/10 text-primary">
              Why Localify
            </span>
            <h2 className="text-balance font-display text-3xl font-bold text-text sm:text-4xl">
              Built around the businesses the internet forgot
            </h2>
          </div>

          <motion.div
            variants={container}
            initial="hidden"
            whileInView="show"
            viewport={{ once: true, amount: 0.15 }}
            className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"
          >
            {FEATURES.map((f) => (
              <motion.div
                key={f.title}
                variants={item}
                whileHover={reduce ? undefined : { y: -4 }}
                transition={{ type: 'spring', stiffness: 300 }}
                className={`card-base relative overflow-hidden p-6 ${f.span} ${
                  f.accent
                    ? 'bg-gradient-to-br from-primary/10 via-surface to-accent/5'
                    : ''
                }`}
              >
                <div
                  className={`mb-4 inline-grid h-11 w-11 place-items-center rounded-xl ${
                    f.accent
                      ? 'bg-primary/15 text-primary'
                      : 'bg-accent/10 text-accent'
                  }`}
                >
                  <f.icon className="h-5 w-5" />
                </div>
                <h3 className="font-display text-lg font-semibold text-text">
                  {f.title}
                </h3>
                <p className="mt-2 text-sm leading-relaxed text-text-muted">
                  {f.desc}
                </p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* STATS */}
      <section className="mx-auto max-w-6xl px-4 py-20 sm:px-6">
        <div className="grid gap-6 sm:grid-cols-3">
          {STATS.map((s) => (
            <div key={s.label} className="card-base p-8 text-center">
              <div className="font-display text-4xl font-extrabold sm:text-5xl">
                <span className="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
                  <CountUp value={s.value} suffix={s.suffix} />
                </span>
              </div>
              <div className="mt-2 text-sm font-medium text-text-muted">
                {s.label}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* CTA BANNER */}
      <section className="px-4 pb-24 sm:px-6">
        <div className="relative mx-auto max-w-5xl overflow-hidden rounded-3xl border border-border bg-gradient-to-br from-primary/20 via-surface to-accent/10 p-10 text-center sm:p-16">
          <div
            aria-hidden="true"
            className="pointer-events-none absolute -right-16 -top-16 h-64 w-64 rounded-full bg-glow-primary blur-3xl"
          />
          <div
            aria-hidden="true"
            className="pointer-events-none absolute -bottom-16 -left-16 h-64 w-64 rounded-full bg-glow-accent blur-3xl"
          />
          <h2 className="text-balance font-display text-3xl font-bold text-text sm:text-4xl">
            {isAuthenticated
              ? 'Pick up where you left off'
              : 'Start discovering today'}
          </h2>
          <p className="mx-auto mt-4 max-w-xl text-text-muted">
            {isAuthenticated
              ? 'Jump back into search and find the offline businesses thriving right around the corner.'
              : 'Create a free account and find the offline businesses thriving right around the corner from you.'}
          </p>
          <motion.div
            whileTap={reduce ? undefined : { scale: 0.96 }}
            className="mt-8 inline-block"
          >
            <Link to={primaryTo} className="btn-primary px-8 py-4 text-base">
              {primaryLabel}
              <ArrowRight className="h-4 w-4" />
            </Link>
          </motion.div>
        </div>
      </section>
    </Layout>
  );
};

export default LandingPage;
