import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';
import {
  MapPin,
  Search,
  PhoneCall,
  Sparkles,
  Map,
  Contact,
  Zap,
  Globe2,
  BadgeCheck,
  ArrowRight,
  Star,
  Phone,
  ShieldCheck,
  Map as MapIcon,
} from 'lucide-react';
import Layout from '../layout/Layout';
import { useAuth } from '../hooks/useAuth';
import Magnetic from '../components/Magnetic';

import { initHeroAnimation } from '../animations/hero';
import { initScrollTakeover } from '../animations/scrollTakeover';
import { initSectionReveals } from '../animations/reveal';
import { initParallax, initTextParallax } from '../animations/parallax';
import { initHoverEffects } from '../animations/hover';
import { initHowItWorks } from '../animations/howItWorks';
import { initFeatures3D } from '../animations/features';
import { initCtaSpotlight } from '../animations/cta';

const HOW_IT_WORKS = [
  {
    icon: MapPin,
    title: 'Set your location',
    desc: 'Pick your state and district, then type your city or town. Takes ten seconds.',
  },
  {
    icon: Search,
    title: 'Search businesses',
    desc: 'We sweep Google Maps for shops, malls, eateries and services around you.',
  },
  {
    icon: PhoneCall,
    title: 'Connect directly',
    desc: 'Get phone numbers, locations and an AI summary — then reach out.',
  },
];

const FEATURES = [
  {
    icon: Map,
    title: 'Google Maps powered',
    desc: 'Accurate, fresh listings pulled straight from Google Places across every category. No outdated directory databases.',
    span: 'lg:col-span-2 lg:row-span-2',
    accent: true,
  },
  {
    icon: Sparkles,
    title: 'AI business summaries',
    desc: 'A friendly, instant read on each place — generated by a local open-source model.',
    span: 'lg:col-span-2',
  },
  {
    icon: Contact,
    title: 'Contact info surfaced',
    desc: 'Phone numbers and addresses up front.',
    span: 'lg:col-span-1',
  },
  {
    icon: Globe2,
    title: 'Offline-first discovery',
    desc: 'Filter to businesses with no website — the ones the web forgot.',
    span: 'lg:col-span-1',
  },
  {
    icon: Zap,
    title: 'Fast & cached',
    desc: 'Parallel lookups and smart caching keep results instant.',
    span: 'lg:col-span-2',
  },
];

const STATS = [
  { value: 10000, suffix: '+', label: 'Businesses indexed' },
  { value: 500, suffix: '+', label: 'Cities covered' },
  { value: 100, suffix: '%', label: 'Free forever' },
];

const PREVIEW_CARDS = [
  {
    name: 'Sharma General Stores',
    category: 'Shops',
    phone: '+91 98765 43210',
    rating: 4.6,
    reviews: 214,
  },
  {
    name: 'Annapurna Family Restaurant',
    category: 'Restaurants',
    phone: '+91 91234 56780',
    rating: 4.8,
    reviews: 532,
  },
  {
    name: 'City Care Pharmacy',
    category: 'Healthcare',
    phone: '+91 99887 76655',
    rating: 4.4,
    reviews: 98,
  },
];

/** Animated count-up that triggers when scrolled into view using ScrollTrigger. */
const CountUp = ({ value, suffix }) => {
  const ref = useRef(null);
  const [display, setDisplay] = useState(0);

  useGSAP(() => {
    const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (prefersReducedMotion) {
      setDisplay(value);
      return;
    }

    const proxy = { val: 0 };
    gsap.to(proxy, {
      val: value,
      duration: 1.6,
      ease: 'power3.out',
      scrollTrigger: {
        trigger: ref.current,
        start: 'top 80%',
      },
      onUpdate: () => setDisplay(Math.round(proxy.val))
    });
  }, { scope: ref });

  return (
    <span ref={ref}>
      {display.toLocaleString('en-IN')}
      {suffix}
    </span>
  );
};

const HeroPreview = () => (
  <div className="hero-preview-panel relative mx-auto w-full max-w-3xl opacity-0 translate-y-12 will-change-transform">
    <div className="absolute -inset-10 -z-10 rounded-[3rem] bg-glow-primary blur-3xl opacity-40" />
    <div className="card-base overflow-hidden p-6 shadow-[0_30px_100px_-20px_rgba(0,0,0,0.8)] border-white/5 bg-surface/60 backdrop-blur-2xl rounded-3xl">
      <div className="mb-5 flex items-center gap-2">
        <span className="h-2.5 w-2.5 rounded-full bg-error/70" />
        <span className="h-2.5 w-2.5 rounded-full bg-primary/60" />
        <span className="h-2.5 w-2.5 rounded-full bg-accent/70" />
        <div className="ml-3 flex-1 rounded-lg bg-surface-2/50 px-3 py-1.5 text-xs text-text-muted border border-white/5">
          Businesses in Nashik, Maharashtra
        </div>
      </div>

      <div className="grid gap-3 sm:grid-cols-3">
        {PREVIEW_CARDS.map((c, i) => (
          <div
            key={c.name}
            className="hero-preview-card rounded-xl border border-white/5 bg-surface-2/40 p-4 opacity-0 translate-y-5 will-change-transform"
          >
            <div className="flex items-start justify-between gap-2 mb-2">
              <div className="font-display text-sm font-bold text-text leading-tight">
                {c.name}
              </div>
            </div>
            <span className="pill border-accent/20 bg-accent/10 text-accent text-[10px] mb-4 inline-flex">
              <Globe2 className="h-3 w-3" />
              No Website
            </span>
            <div className="flex flex-col gap-2 mt-auto pt-2 border-t border-white/5">
              <div className="flex items-center gap-2 text-xs text-text-muted">
                <Phone className="h-3.5 w-3.5 text-accent" />
                {c.phone}
              </div>
              <div className="flex items-center justify-between mt-1">
                <span className="text-xs font-medium text-primary bg-primary/10 px-2 py-0.5 rounded">
                  {c.category}
                </span>
                <span className="flex items-center gap-1 text-xs text-text-muted font-medium">
                  <Star className="h-3.5 w-3.5 fill-accent text-accent" />
                  {c.rating}
                </span>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>

    <div className="hero-preview-chip absolute -top-5 -right-5 max-w-[12rem] rounded-xl border border-white/10 bg-surface p-3 shadow-[0_20px_40px_rgba(0,0,0,0.6)] opacity-0 scale-90 will-change-transform z-20 backdrop-blur-xl">
      <div className="mb-1.5 flex items-center gap-1.5 text-[10px] font-bold text-primary tracking-wide uppercase">
        <Sparkles className="h-3.5 w-3.5" />
        AI insight
      </div>
      <p className="text-[11px] leading-relaxed text-text-muted font-medium">
        “A beloved neighbourhood store known for friendly service and fair prices…”
      </p>
    </div>
  </div>
);

const LandingPage = () => {
  const { isAuthenticated, hasAddress } = useAuth();
  const mainRef = useRef(null);
  const scrollTakeoverRef = useRef(null);
  const hiwRef = useRef(null);
  const hiwContainerRef = useRef(null);
  const featuresRef = useRef(null);
  const ctaRef = useRef(null);

  const primaryTo = isAuthenticated
    ? hasAddress
      ? '/search'
      : '/address-setup'
    : '/signup';
  const primaryLabel = isAuthenticated ? 'Go to Search' : 'Get Started Free';

  useGSAP(() => {
    let heroCleanup = () => {};
    let takeoverTimeline = null;

    let mm = gsap.matchMedia();

    // DESKTOP ( >= 768px )
    mm.add("(min-width: 768px)", () => {
      heroCleanup = initHeroAnimation(true);
      takeoverTimeline = initScrollTakeover(scrollTakeoverRef.current, true);
      
      const hiwTimeline = initHowItWorks(hiwRef.current, hiwContainerRef.current, true);
      initFeatures3D(featuresRef.current, true);
      const ctaCleanup = initCtaSpotlight(ctaRef.current, true);

      initSectionReveals(gsap.utils.toArray('.reveal-section'), true);
      initParallax(mainRef.current, true);
      initTextParallax(mainRef.current);
      
      const hoverCleanup = initHoverEffects(gsap.utils.toArray('.hover-card'));

      return () => {
        heroCleanup();
        if (takeoverTimeline) takeoverTimeline.kill();
        if (hiwTimeline) hiwTimeline.kill();
        if (ctaCleanup) ctaCleanup();
        if (hoverCleanup) hoverCleanup();
      };
    });

    // MOBILE ( < 768px )
    mm.add("(max-width: 767px)", () => {
      heroCleanup = initHeroAnimation(false);
      takeoverTimeline = initScrollTakeover(scrollTakeoverRef.current, false);
      
      const hiwTimeline = initHowItWorks(hiwRef.current, hiwContainerRef.current, false);
      initFeatures3D(featuresRef.current, false);
      const ctaCleanup = initCtaSpotlight(ctaRef.current, false);

      initSectionReveals(gsap.utils.toArray('.reveal-section'), false);
      initParallax(mainRef.current, false);

      return () => {
        heroCleanup();
        if (takeoverTimeline) takeoverTimeline.kill();
        if (hiwTimeline) hiwTimeline.kill();
        if (ctaCleanup) ctaCleanup();
      };
    });

    return () => mm.revert();
  }, { scope: mainRef });

  return (
    <Layout>
      <Helmet>
        <title>Localify — Find the Hidden Businesses Your City Never Told You About</title>
      </Helmet>

      <div ref={mainRef} className="relative">
        {/* HERO */}
        <section className="relative overflow-visible pt-24 pb-32 lg:pt-32 lg:pb-40 min-h-[85vh] flex flex-col justify-start z-20">
          {/* Subtle grid background to match layout */}
          <div className="absolute inset-0 bg-[url('/grid.svg')] bg-center opacity-30 [mask-image:linear-gradient(180deg,white,rgba(255,255,255,0))]" />
          
          <div className="relative z-10 mx-auto w-full max-w-6xl px-4 sm:px-6">
            <div className="flex flex-col items-center text-center max-w-3xl mx-auto">
              <span className="hero-pill pill mb-6 border-primary/30 bg-primary/10 text-primary opacity-0 translate-y-4 will-change-transform shadow-[0_0_20px_rgba(0,212,170,0.15)] text-xs">
                <Sparkles className="h-3.5 w-3.5" />
                Powered by Google Maps + local AI
              </span>

              <h1 className="hero-title text-balance font-display text-4xl font-black leading-[1.05] tracking-tight text-text sm:text-5xl xl:text-6xl overflow-hidden">
                Find the{' '}
                <span className="bg-gradient-to-r from-primary via-accent to-primary bg-clip-text text-transparent inline-block pb-1 sm:pb-2">
                  Hidden Businesses
                </span>
                <br />
                Your City Never Told You About
              </h1>

              <p className="hero-desc mt-6 max-w-xl text-base text-text-muted sm:text-lg opacity-0 translate-y-4 will-change-transform leading-relaxed">
                Thousands of shops, malls and family-run businesses operate entirely
                offline. Localify uncovers them across your city, surfaces their
                contact details, and explains what they do with instant AI summaries.
              </p>

              <div className="hero-buttons mt-10 flex flex-col items-center gap-3 sm:flex-row opacity-0 translate-y-4 will-change-transform">
                <Magnetic strength={0.4}>
                  <Link to={primaryTo} className="btn-primary px-7 py-3.5 text-base rounded-2xl shadow-[0_0_40px_rgba(0,212,170,0.2)] border border-primary/20">
                    {primaryLabel}
                    <ArrowRight className="h-4 w-4" />
                  </Link>
                </Magnetic>
                <Magnetic strength={0.3}>
                  <a href="#how-it-works" className="btn-ghost px-7 py-3.5 text-base rounded-2xl backdrop-blur-md bg-surface-2/50 border-white/5 hover:bg-surface-2">
                    See How It Works
                  </a>
                </Magnetic>
              </div>

              <div className="hero-trust mt-8 flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-xs text-text-muted opacity-0 font-medium">
                <span className="inline-flex items-center gap-1.5"><ShieldCheck className="h-4 w-4 text-accent" />No spam, ever</span>
                <span className="inline-flex items-center gap-1.5"><BadgeCheck className="h-4 w-4 text-accent" />Free forever</span>
                <span className="inline-flex items-center gap-1.5"><Zap className="h-4 w-4 text-accent" />Instant results</span>
              </div>
            </div>

            {/* Overlapping Product Preview */}
            <div className="mt-12 sm:mt-16 relative z-20 w-full">
              <HeroPreview />
              
              {/* Floating Stats Connector */}
              <div className="reveal-section absolute -bottom-24 left-1/2 -translate-x-1/2 w-full max-w-4xl px-4 z-30 pointer-events-none">
                <div className="card-base bg-surface/60 backdrop-blur-2xl border border-white/10 p-5 sm:p-6 flex flex-col sm:flex-row justify-around items-center gap-6 shadow-[0_30px_60px_rgba(0,0,0,0.6)] rounded-2xl pointer-events-auto">
                  {STATS.map((s) => (
                    <div key={s.label} className="text-center flex-1">
                      <div className="font-display text-3xl font-extrabold text-white">
                        <CountUp value={s.value} suffix={s.suffix} />
                      </div>
                      <div className="mt-1 text-xs font-medium text-text-muted uppercase tracking-wider">{s.label}</div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* SCROLL TAKEOVER */}
        <section ref={scrollTakeoverRef} className="relative h-screen w-full bg-surface-2 overflow-hidden flex items-center justify-center border-t border-white/5 z-10 pt-16">
          <div className="takeover-intro-text absolute inset-0 flex flex-col items-center justify-center z-30 pointer-events-none">
            <span className="pill mb-3 border-accent/40 bg-accent/10 text-accent shadow-[0_0_20px_rgba(79,70,229,0.15)] text-xs">Deep Discovery</span>
            <h2 className="font-display text-3xl font-bold text-white text-center max-w-xl px-4 text-balance leading-tight tracking-tight sm:text-4xl">
              We look past the first page of Google to find what really matters.
            </h2>
          </div>

          <div className="takeover-map-container absolute inset-0 flex items-center justify-center will-change-transform">
            <svg viewBox="0 0 800 600" className="w-[100vw] h-auto max-h-[100vh] opacity-40" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path className="takeover-svg-path" d="M100 300 Q 250 100 400 300 T 700 300" stroke="#00D4AA" strokeWidth="4" strokeLinecap="round" />
              <path className="takeover-svg-path" d="M150 400 Q 300 500 450 350 T 750 400" stroke="#4F46E5" strokeWidth="4" strokeLinecap="round" strokeDasharray="10 10" />
              <circle className="takeover-svg-path" cx="400" cy="300" r="100" stroke="#FF5370" strokeWidth="2" />
              <circle className="takeover-svg-path" cx="250" cy="200" r="15" stroke="#00D4AA" strokeWidth="6" />
              <circle className="takeover-svg-path" cx="550" cy="450" r="15" stroke="#4F46E5" strokeWidth="6" />
            </svg>
          </div>

          <div className="absolute inset-0 flex items-center justify-around px-4 sm:px-12 pointer-events-none z-40">
            <div className="takeover-hud-card card-base bg-surface/70 backdrop-blur-xl border-white/10 p-5 max-w-[16rem] opacity-0 translate-y-10 will-change-transform rounded-2xl">
              <MapIcon className="h-6 w-6 text-primary mb-3" />
              <h4 className="font-bold text-base text-white">Hyper-Local Grid</h4>
              <p className="text-xs text-text-muted mt-1.5 leading-relaxed">Scanning every coordinate within a 10km radius of your search location.</p>
            </div>
            
            <div className="takeover-hud-card card-base bg-surface/70 backdrop-blur-xl border-white/10 p-5 max-w-[16rem] opacity-0 translate-y-10 will-change-transform mt-56 rounded-2xl">
              <Zap className="h-6 w-6 text-accent mb-3" />
              <h4 className="font-bold text-base text-white">Real-Time Sync</h4>
              <p className="text-xs text-text-muted mt-1.5 leading-relaxed">Pulling the freshest data instantly without waiting for manual scrapes.</p>
            </div>
          </div>
        </section>

        {/* HOW IT WORKS (Offset Editorial Layout) */}
        <section ref={hiwRef} id="how-it-works" className="relative z-10 w-full overflow-hidden bg-bg py-24 sm:py-32">
          <div className="mx-auto max-w-6xl px-4 sm:px-6">
            <div className="mb-20 md:ml-auto md:w-1/2 md:pl-10 lg:pl-16 border-l border-primary/20">
              <span className="pill mb-4 border-primary/30 bg-primary/10 text-primary text-xs">The Process</span>
              <h2 className="text-balance font-display text-3xl font-bold text-text sm:text-4xl tracking-tight leading-tight">
                Three steps from curiosity to a phone call.
              </h2>
            </div>
          </div>

          {/* Horizontal scroll container */}
          <div className="relative mx-auto max-w-6xl px-4 sm:px-6">
            <div ref={hiwContainerRef} className="flex gap-6 sm:gap-8 w-[max-content] pb-8 pr-[50vw]">
              <div className="hiw-progress-line absolute top-1/2 left-4 h-1 w-[200vw] -translate-y-1/2 bg-gradient-to-r from-primary/30 to-accent/30 -z-10 rounded-full hidden md:block" />
              {HOW_IT_WORKS.map((step, i) => (
                <div key={step.title} className="hiw-card card-base relative p-8 sm:p-10 w-[85vw] md:w-[28rem] flex-shrink-0 bg-surface/50 backdrop-blur-xl border-white/5 rounded-3xl">
                  <div className="mb-6 inline-grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br from-primary/20 to-accent/20 text-primary ring-1 ring-border shadow-lg">
                    <step.icon className="h-7 w-7" />
                  </div>
                  <div className="mb-2 font-display text-[11px] font-bold text-accent tracking-widest uppercase">Step {i + 1}</div>
                  <h3 className="font-display text-2xl font-semibold text-text">{step.title}</h3>
                  <p className="mt-3 text-base leading-relaxed text-text-muted">{step.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* FEATURES — Asymmetrical Bento Box */}
        <section ref={featuresRef} className="bg-surface/40 relative z-10 overflow-hidden py-24 sm:py-32 border-t border-white/5">
          <div className="mx-auto max-w-6xl px-4 sm:px-6">
            <div className="mb-16 flex flex-col items-center text-center">
              <span className="pill mb-5 border-primary/40 bg-primary/10 text-primary shadow-[0_0_20px_rgba(0,212,170,0.15)] text-xs">Why Localify</span>
              <h2 className="text-balance font-display text-3xl font-bold text-text sm:text-4xl lg:text-5xl tracking-tight max-w-2xl leading-tight">
                Built around the businesses the internet forgot
              </h2>
            </div>

            <div className="feature-grid-container grid gap-5 sm:gap-6 grid-cols-1 md:grid-cols-2 lg:grid-cols-4 lg:grid-rows-2 perspective-[2000px] max-w-5xl mx-auto">
              {FEATURES.map((f, i) => (
                <div
                  key={f.title}
                  className={`feature-3d-card hover-card card-base relative overflow-hidden p-6 sm:p-8 rounded-3xl border-white/5 ${f.span} ${
                    f.accent ? 'bg-gradient-to-br from-primary/10 via-surface to-accent/5' : 'bg-surface/60'
                  }`}
                >
                  <div className={`mb-5 inline-grid h-12 w-12 place-items-center rounded-2xl ${
                    f.accent ? 'bg-primary/20 text-primary shadow-[0_0_30px_rgba(0,212,170,0.3)]' : 'bg-accent/10 text-accent'
                  }`}>
                    <f.icon className="h-5 w-5" />
                  </div>
                  <h3 className={`font-display font-semibold text-text ${f.accent ? 'text-2xl mb-3' : 'text-lg mb-2'}`}>{f.title}</h3>
                  <p className={`leading-relaxed text-text-muted ${f.accent ? 'text-base max-w-sm' : 'text-sm'}`}>{f.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA BANNER (Immersive Wrap) */}
        <section ref={ctaRef} className="relative overflow-hidden z-20 min-h-[90vh] flex items-center justify-center bg-bg pb-16">
          <div className="cta-spotlight-box absolute inset-x-4 inset-y-8 sm:inset-x-8 sm:inset-y-16 rounded-[2.5rem] border border-border bg-gradient-to-b from-surface/50 to-bg pointer-events-none">
            {/* Ambient glows bleeding to edges */}
            <div className="absolute -left-1/4 -top-1/4 h-[70vw] w-[70vw] rounded-full bg-primary/10 blur-[120px]" />
            <div className="absolute -bottom-1/4 -right-1/4 h-[70vw] w-[70vw] rounded-full bg-accent/10 blur-[120px]" />
          </div>

          <div className="relative z-30 mx-auto w-full max-w-3xl px-4 py-24 text-center pointer-events-auto">
            <span className="pill mb-6 border-accent/40 bg-accent/10 text-accent shadow-[0_0_20px_rgba(79,70,229,0.2)] text-xs">
              Start Exploring
            </span>
            <h2 className="cta-title text-balance font-display text-4xl font-black uppercase tracking-tighter text-white sm:text-5xl lg:text-6xl mb-6 leading-[0.95]">
              {isAuthenticated ? 'Pick up where you left off' : 'Ready to find the hidden gems?'}
            </h2>
            <p className="mx-auto mb-10 max-w-xl text-base text-text-muted sm:text-lg leading-relaxed">
              {isAuthenticated
                ? 'Jump back into search and find the offline businesses thriving right around the corner.'
                : 'Join today and discover the shops, services, and eateries that Google Maps forgot.'}
            </p>
            <div className="flex justify-center">
              <Magnetic strength={0.4}>
                <Link to={primaryTo} className="btn-primary rounded-2xl px-10 py-4 text-base font-bold shadow-[0_0_40px_rgba(0,212,170,0.2)] border border-primary/20">
                  {primaryLabel}
                  <ArrowRight className="h-4 w-4 ml-2" />
                </Link>
              </Magnetic>
            </div>
          </div>
        </section>
      </div>
    </Layout>
  );
};

export default LandingPage;
