// Indian states & union territories with their major districts.
// District lists are representative (well-known districts), not exhaustive.

export const STATE_DISTRICTS = {
  'andhra-pradesh': [
    'Anantapur',
    'Chittoor',
    'East Godavari',
    'Guntur',
    'Krishna',
    'Kurnool',
    'Nellore',
    'Prakasam',
    'Srikakulam',
    'Visakhapatnam',
    'Vizianagaram',
    'West Godavari',
    'Kadapa',
  ],
  'arunachal-pradesh': [
    'Itanagar',
    'Tawang',
    'West Kameng',
    'East Kameng',
    'Papum Pare',
    'Lower Subansiri',
    'Upper Subansiri',
    'Lohit',
    'Changlang',
    'Tirap',
  ],
  assam: [
    'Kamrup Metropolitan',
    'Kamrup',
    'Cachar',
    'Dibrugarh',
    'Nagaon',
    'Sonitpur',
    'Barpeta',
    'Dhubri',
    'Jorhat',
    'Tinsukia',
    'Sivasagar',
    'Golaghat',
  ],
  bihar: [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Purnia',
    'Darbhanga',
    'Begusarai',
    'Nalanda',
    'Saran',
    'Rohtas',
    'Katihar',
    'East Champaran',
    'West Champaran',
  ],
  chhattisgarh: [
    'Raipur',
    'Bilaspur',
    'Durg',
    'Korba',
    'Raigarh',
    'Rajnandgaon',
    'Jagdalpur',
    'Bastar',
    'Dhamtari',
    'Mahasamund',
  ],
  goa: ['North Goa', 'South Goa'],
  gujarat: [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Junagadh',
    'Gandhinagar',
    'Anand',
    'Kutch',
    'Mehsana',
    'Bharuch',
    'Navsari',
  ],
  haryana: [
    'Gurugram',
    'Faridabad',
    'Panipat',
    'Ambala',
    'Karnal',
    'Hisar',
    'Rohtak',
    'Sonipat',
    'Yamunanagar',
    'Panchkula',
    'Sirsa',
    'Bhiwani',
  ],
  'himachal-pradesh': [
    'Shimla',
    'Kangra',
    'Mandi',
    'Solan',
    'Kullu',
    'Hamirpur',
    'Una',
    'Bilaspur',
    'Chamba',
    'Sirmaur',
    'Kinnaur',
    'Lahaul and Spiti',
  ],
  jharkhand: [
    'Ranchi',
    'Dhanbad',
    'Jamshedpur',
    'Bokaro',
    'Hazaribagh',
    'Deoghar',
    'Giridih',
    'Dumka',
    'Palamu',
    'Ramgarh',
  ],
  karnataka: [
    'Bengaluru Urban',
    'Bengaluru Rural',
    'Mysuru',
    'Mangaluru (Dakshina Kannada)',
    'Hubballi-Dharwad',
    'Belagavi',
    'Kalaburagi',
    'Ballari',
    'Vijayapura',
    'Shivamogga',
    'Tumakuru',
    'Udupi',
    'Davanagere',
  ],
  kerala: [
    'Thiruvananthapuram',
    'Ernakulam',
    'Kozhikode',
    'Thrissur',
    'Kollam',
    'Kannur',
    'Alappuzha',
    'Palakkad',
    'Malappuram',
    'Kottayam',
    'Pathanamthitta',
    'Idukki',
    'Wayanad',
    'Kasaragod',
  ],
  'madhya-pradesh': [
    'Bhopal',
    'Indore',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Sagar',
    'Rewa',
    'Satna',
    'Ratlam',
    'Dewas',
    'Chhindwara',
    'Vidisha',
  ],
  maharashtra: [
    'Mumbai City',
    'Mumbai Suburban',
    'Pune',
    'Nashik',
    'Nagpur',
    'Aurangabad',
    'Thane',
    'Solapur',
    'Kolhapur',
    'Sangli',
    'Satara',
    'Ahmednagar',
    'Jalgaon',
    'Amravati',
    'Akola',
    'Nanded',
    'Latur',
    'Osmanabad',
    'Beed',
    'Washim',
    'Yavatmal',
    'Buldhana',
    'Chandrapur',
    'Gadchiroli',
    'Wardha',
    'Bhandara',
    'Gondia',
    'Raigad',
    'Ratnagiri',
    'Sindhudurg',
    'Dhule',
    'Nandurbar',
    'Palghar',
  ],
  manipur: [
    'Imphal West',
    'Imphal East',
    'Thoubal',
    'Bishnupur',
    'Churachandpur',
    'Senapati',
    'Ukhrul',
    'Chandel',
  ],
  meghalaya: [
    'East Khasi Hills',
    'West Khasi Hills',
    'Ri-Bhoi',
    'West Garo Hills',
    'East Garo Hills',
    'Jaintia Hills',
    'South Garo Hills',
  ],
  mizoram: [
    'Aizawl',
    'Lunglei',
    'Champhai',
    'Kolasib',
    'Serchhip',
    'Mamit',
    'Lawngtlai',
    'Saiha',
  ],
  nagaland: [
    'Kohima',
    'Dimapur',
    'Mokokchung',
    'Tuensang',
    'Wokha',
    'Zunheboto',
    'Mon',
    'Phek',
  ],
  odisha: [
    'Khordha (Bhubaneswar)',
    'Cuttack',
    'Ganjam',
    'Sundargarh',
    'Sambalpur',
    'Balasore',
    'Puri',
    'Mayurbhanj',
    'Koraput',
    'Angul',
    'Rourkela',
  ],
  punjab: [
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'Mohali',
    'Hoshiarpur',
    'Pathankot',
    'Moga',
    'Firozpur',
    'Sangrur',
  ],
  rajasthan: [
    'Jaipur',
    'Jodhpur',
    'Udaipur',
    'Kota',
    'Ajmer',
    'Bikaner',
    'Alwar',
    'Bhilwara',
    'Sikar',
    'Bharatpur',
    'Pali',
    'Sri Ganganagar',
  ],
  sikkim: ['East Sikkim (Gangtok)', 'West Sikkim', 'North Sikkim', 'South Sikkim'],
  'tamil-nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli',
    'Salem',
    'Tirunelveli',
    'Erode',
    'Vellore',
    'Thoothukudi',
    'Thanjavur',
    'Dindigul',
    'Kanchipuram',
    'Tiruppur',
  ],
  telangana: [
    'Hyderabad',
    'Rangareddy',
    'Medchal-Malkajgiri',
    'Warangal Urban',
    'Karimnagar',
    'Khammam',
    'Nizamabad',
    'Nalgonda',
    'Mahbubnagar',
    'Adilabad',
  ],
  tripura: [
    'West Tripura (Agartala)',
    'South Tripura',
    'North Tripura',
    'Dhalai',
    'Gomati',
    'Khowai',
    'Unakoti',
    'Sepahijala',
  ],
  'uttar-pradesh': [
    'Lucknow',
    'Kanpur Nagar',
    'Agra',
    'Varanasi',
    'Prayagraj',
    'Meerut',
    'Ghaziabad',
    'Gautam Buddha Nagar (Noida)',
    'Bareilly',
    'Aligarh',
    'Moradabad',
    'Gorakhpur',
    'Saharanpur',
    'Jhansi',
  ],
  uttarakhand: [
    'Dehradun',
    'Haridwar',
    'Nainital',
    'Udham Singh Nagar',
    'Pauri Garhwal',
    'Tehri Garhwal',
    'Almora',
    'Chamoli',
    'Pithoragarh',
    'Rudraprayag',
  ],
  'west-bengal': [
    'Kolkata',
    'North 24 Parganas',
    'South 24 Parganas',
    'Howrah',
    'Hooghly',
    'Darjeeling',
    'Bardhaman',
    'Nadia',
    'Murshidabad',
    'Malda',
    'Siliguri (Jalpaiguri)',
    'Paschim Medinipur',
  ],

  // Union Territories
  'andaman-and-nicobar-islands': [
    'South Andaman (Port Blair)',
    'North and Middle Andaman',
    'Nicobar',
  ],
  chandigarh: ['Chandigarh'],
  'dadra-and-nagar-haveli-and-daman-and-diu': [
    'Dadra and Nagar Haveli',
    'Daman',
    'Diu',
  ],
  delhi: [
    'New Delhi',
    'Central Delhi',
    'North Delhi',
    'South Delhi',
    'East Delhi',
    'West Delhi',
    'North East Delhi',
    'North West Delhi',
    'South West Delhi',
    'Shahdara',
  ],
  'jammu-and-kashmir': [
    'Srinagar',
    'Jammu',
    'Anantnag',
    'Baramulla',
    'Pulwama',
    'Kupwara',
    'Udhampur',
    'Kathua',
    'Budgam',
  ],
  ladakh: ['Leh', 'Kargil'],
  lakshadweep: ['Lakshadweep'],
  puducherry: ['Puducherry', 'Karaikal', 'Mahe', 'Yanam'],
};

// Human-readable labels for each state/UT value.
const STATE_LABELS = {
  'andhra-pradesh': 'Andhra Pradesh',
  'arunachal-pradesh': 'Arunachal Pradesh',
  assam: 'Assam',
  bihar: 'Bihar',
  chhattisgarh: 'Chhattisgarh',
  goa: 'Goa',
  gujarat: 'Gujarat',
  haryana: 'Haryana',
  'himachal-pradesh': 'Himachal Pradesh',
  jharkhand: 'Jharkhand',
  karnataka: 'Karnataka',
  kerala: 'Kerala',
  'madhya-pradesh': 'Madhya Pradesh',
  maharashtra: 'Maharashtra',
  manipur: 'Manipur',
  meghalaya: 'Meghalaya',
  mizoram: 'Mizoram',
  nagaland: 'Nagaland',
  odisha: 'Odisha',
  punjab: 'Punjab',
  rajasthan: 'Rajasthan',
  sikkim: 'Sikkim',
  'tamil-nadu': 'Tamil Nadu',
  telangana: 'Telangana',
  tripura: 'Tripura',
  'uttar-pradesh': 'Uttar Pradesh',
  uttarakhand: 'Uttarakhand',
  'west-bengal': 'West Bengal',
  'andaman-and-nicobar-islands': 'Andaman and Nicobar Islands',
  chandigarh: 'Chandigarh',
  'dadra-and-nagar-haveli-and-daman-and-diu':
    'Dadra and Nagar Haveli and Daman and Diu',
  delhi: 'Delhi (NCT)',
  'jammu-and-kashmir': 'Jammu and Kashmir',
  ladakh: 'Ladakh',
  lakshadweep: 'Lakshadweep',
  puducherry: 'Puducherry',
};

// Sorted array of { value, label } for the state dropdown.
export const STATES = Object.keys(STATE_LABELS)
  .map((value) => ({ value, label: STATE_LABELS[value] }))
  .sort((a, b) => a.label.localeCompare(b.label));

/**
 * Get districts for a given state value. Returns [] if unknown.
 */
export const getDistricts = (stateValue) =>
  STATE_DISTRICTS[stateValue] ? [...STATE_DISTRICTS[stateValue]] : [];

/**
 * Resolve a state value to its display label.
 */
export const getStateLabel = (stateValue) =>
  STATE_LABELS[stateValue] || stateValue || '';
