// Same questions the website uses (client/src/utils/surveyQuestions.js) so the
// AI generator behaves identically from the app.
export const getSurveyQuestions = () => [
  { id: 'Color Theme', title: 'What should the main color theme be?', options: ['Dark Mode (deep black / charcoal with bright glowing highlights)', 'Light Mode (white / soft gray with clean crisp borders)', 'Vibrant & Colorful (bold, saturated, energetic colors everywhere)', 'Soft & Calm (gentle pastels and muted, relaxing tones)'] },
  { id: 'Visual Aesthetic', title: 'What overall style/personality should it have?', options: ['Minimal & Clean (lots of space, simple, uncluttered)', 'Bold & Punchy (big text, strong contrast, high energy)', 'Luxury & Elegant (premium, refined, sophisticated)', 'Playful & Friendly (fun, approachable, rounded, cheerful)', 'Corporate & Professional (trustworthy, structured, business-like)', 'Futuristic & Techy (sleek, neon, high-tech, cutting-edge)'] },
  { id: 'Card & Surface Style', title: 'How should cards and panels look?', options: ['Glassmorphism (frosted, see-through glass with blur)', 'Solid Cards with Shadows (raised, floating, clear depth)', 'Flat & Bordered (clean outlines, no shadows, modern-flat)', 'Soft & Rounded (gentle pillowy surfaces, subtle depth)'] },
  { id: 'Gradients', title: 'How much should color gradients be used?', options: ['Rich Gradients (colorful gradient backgrounds and buttons everywhere)', 'Subtle Gradient Accents (a few tasteful gradient touches)', 'Solid Colors Only (flat, single colors — no gradients)'] },
  { id: 'Special Effects', title: 'What kind of visual effects do you want?', options: ['Glows & Neon (glowing buttons, soft light halos, neon accents)', 'Deep Shadows & Depth (strong drop-shadows, layered 3D feel)', 'Textured (subtle grain / noise / mesh background texture)', 'Clean & Flat (no glows or heavy effects — crisp and simple)'] },
  { id: 'Corner Style', title: 'How should the edges and corners look?', options: ['Very Rounded & Soft (big friendly rounded corners)', 'Slightly Rounded (modern, gentle corners)', 'Sharp & Square (crisp, angular, structured edges)', 'Pill-Shaped Buttons (fully rounded capsule buttons)'] },
  { id: 'Layout Style', title: 'How should the website be organized?', options: ['Neat Boxes & Cards (everything in its own separate card)', 'Full-Screen & Immersive (images and backgrounds stretch edge-to-edge)', 'Classic & Simple (straightforward text blocks and standard sections)', 'Modern & Floating (elements float freely without strict borders)'] },
  { id: 'Spacing & Density', title: 'How much breathing room should there be?', options: ['Airy & Spacious (lots of whitespace, big margins, relaxed)', 'Balanced (comfortable, even spacing)', 'Compact & Dense (tighter layout, more content per screen)'] },
  { id: 'Animations', title: 'How much motion and animation do you want?', options: ['Dramatic (elements slide/zoom in, parallax scrolling, floating items)', 'Smooth & Subtle (gentle fades and soft hover effects)', 'Playful (bouncy, springy, fun little movements)', 'None (completely static and extremely fast)'] },
  { id: 'Typography Personality', title: 'What should the text/fonts feel like?', options: ['Modern Sans-Serif (clean, geometric, contemporary)', 'Elegant Serif (classy, editorial, sophisticated)', 'Bold Display Headlines (big, heavy, attention-grabbing titles)', 'Techy / Monospace Accents (sleek, code-like, precise)'] },
  { id: 'Hero Section Style', title: 'How should the top banner look?', options: ['Big Background Photo (full-width business photo with text over it)', 'Split Layout (headline text on one side, image on the other)', 'Centered & Minimal (bold centered headline, clean background)', 'Gradient / Color Backdrop (colorful gradient behind the headline)'] },
  { id: 'Content Amount', title: 'How much information should each section show?', options: ['Very Detailed (rich text, descriptions, and feature lists)', 'Quick & Easy (just the most important bullet points)', 'Mainly Visual (big images, very little text)', 'Balanced (a good mix of a few paragraphs and images)'] },
  { id: 'Main Goal', title: 'What is the main thing you want visitors to do?', options: ['Book an appointment or request a quote', 'Call the business immediately', 'Find the physical location on a map', 'Browse services and learn about the business'] },
];
